/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    GoalDays: typeof import('./src/components/GoalDays.vue')['default']
    ProgressStreak: typeof import('./src/components/ProgressStreak.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
